import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-QLFJTWYPGW"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments)}
            gtag('js', new Date());
            gtag('config', 'G-QLFJTWYPGW');
          `}
        </Script>
      <body
        style={{
          backgroundImage: `url("yulduz.png")`,
          backgroundPosition: "center",
          backgroundAttachment: "fixed",
          margin: 0,
          width: "100%",
          height: "100%",
          overflowX: "hidden",
        }}
        className="antialiased"
      >
        <div style={{ minHeight: "100vh", overflowY: "auto" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
