import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{
        backgroundImage: `url("yulduz.png")`,
        width: "100%",
        height: "100vh",
      }} className="antialiased">
        {children}
      </body>
    </html>
  );
}
